'use strict';

const { DynamoDBClient } = require('@aws-sdk/client-dynamodb');
const { DynamoDBDocumentClient, PutCommand, QueryCommand } = require('@aws-sdk/lib-dynamodb');
const https = require('https');
const { S3Client, PutObjectCommand, GetObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const crypto = require('crypto');

const REQUIRED_ENV_VARS = [
  'DYNAMODB_TABLE_SYMPTOMS',
  'DYNAMODB_TABLE_CONVERSATIONS',
  'REPORTS_BUCKET',
  'COGNITO_USER_POOL_ID',
  'COGNITO_CLIENT_ID',
  'GROQ_API_KEY',
];

let configError = null;
const missingVars = REQUIRED_ENV_VARS.filter((v) => !process.env[v]);
if (missingVars.length > 0) {
  configError = `Missing required environment variables: ${missingVars.join(', ')}`;
}

const dynamoClient = new DynamoDBClient({});
const docClient = DynamoDBDocumentClient.from(dynamoClient);
const s3Client = new S3Client({});

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type,Authorization',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Content-Type': 'application/json',
};

function response(statusCode, body) {
  return { statusCode, headers: CORS_HEADERS, body: JSON.stringify(body) };
}

function callGroq(prompt) {
  return new Promise((resolve, reject) => {
    const body = JSON.stringify({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 1500,
      temperature: 0.7,
    });
    const options = {
      hostname: 'api.groq.com',
      path: '/openai/v1/chat/completions',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${process.env.GROQ_API_KEY}`,
        'Content-Length': Buffer.byteLength(body),
      },
    };
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.choices?.[0]?.message?.content) {
            resolve(parsed.choices[0].message.content.trim());
          } else {
            reject(new Error(parsed.error?.message || 'Unexpected response'));
          }
        } catch (e) { reject(e); }
      });
    });
    req.on('error', reject);
    req.setTimeout(25000, () => { req.destroy(); reject(new Error('Timeout')); });
    req.write(body);
    req.end();
  });
}

async function handleGenerateReport(userId, body) {
  const parsed = JSON.parse(body || '{}');
  const fromDate = parsed.fromDate || new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
  const toDate = parsed.toDate || new Date().toISOString().split('T')[0];

  const fromTimestamp = new Date(fromDate + 'T00:00:00.000Z').toISOString();
  const toTimestamp = new Date(toDate + 'T23:59:59.999Z').toISOString();

  const symptomsResult = await docClient.send(
    new QueryCommand({
      TableName: process.env.DYNAMODB_TABLE_SYMPTOMS,
      KeyConditionExpression: 'userId = :uid AND #ts BETWEEN :from AND :to',
      ExpressionAttributeNames: { '#ts': 'timestamp' },
      ExpressionAttributeValues: { ':uid': userId, ':from': fromTimestamp, ':to': toTimestamp },
    })
  );

  const symptoms = symptomsResult.Items || [];

  const symptomList = symptoms.length > 0
    ? symptoms.map(s => `Date: ${new Date(s.timestamp).toLocaleDateString('en-US', {weekday:'short',month:'short',day:'numeric',year:'numeric'})}, Type: ${s.symptomType}, Severity: ${s.severity}/10, Notes: ${s.notes || 'None'}`).join('\n')
    : 'No symptoms were logged during this period.';

  let summary;
  try {
    const prompt = `You are SheHealth AI, a women's health assistant generating a medical report for a doctor.

Patient symptom log from ${fromDate} to ${toDate}:
${symptomList}

Write a detailed, professional medical report. IMPORTANT FORMATTING RULES:
- Do NOT use asterisks (**) for bold or any markdown formatting
- Use UPPERCASE for section headings
- Use a dash (-) at the start of bullet points
- Write in plain text that will be converted to HTML

Structure the report with these exact sections:

PATIENT HEALTH SUMMARY
[Write 2-3 sentences summarizing overall health status]

SYMPTOM ANALYSIS
- [List each symptom with frequency and severity]
- [Include date patterns if visible]
- [Note any worsening or improving trends]

CLINICAL OBSERVATIONS
- [Clinical interpretation of symptom patterns]
- [Any concerning combinations of symptoms]
- [Hormonal or cyclical patterns if applicable]

RECOMMENDATIONS
- [Specific tests or examinations to consider]
- [Lifestyle recommendations]
- [Follow-up timeline suggestion]

DISCLAIMER
This report was automatically generated by SheHealth AI Assistant based on patient self-reported symptom data. It should be reviewed by a qualified physician and does not constitute a medical diagnosis.

Use professional medical language. Be thorough and specific.`;
    summary = await callGroq(prompt);
  } catch (err) {
    console.error('Groq error:', err);
    return response(500, { message: 'Something went wrong generating your report. Please try again.' });
  }

  const reportId = crypto.randomUUID();
  const reportDate = new Date().toISOString().split('T')[0];
  const s3Key = `reports/${userId}/${reportId}.txt`;

  await docClient.send(new PutCommand({
    TableName: process.env.DYNAMODB_TABLE_CONVERSATIONS,
    Item: {
      userId,
      recordId: `report#${reportId}`,
      recordType: 'report',
      content: summary,
      reportDate,
      fromDate,
      toDate,
      symptomCount: symptoms.length,
      s3Key,
      createdAt: new Date().toISOString(),
    },
  }));

  await s3Client.send(new PutObjectCommand({
    Bucket: process.env.REPORTS_BUCKET,
    Key: s3Key,
    Body: summary,
    ContentType: 'text/plain',
  }));

  return response(200, { reportId, summary, date: reportDate, fromDate, toDate, symptomCount: symptoms.length });
}

async function handleGetReports(userId) {
  const result = await docClient.send(
    new QueryCommand({
      TableName: process.env.DYNAMODB_TABLE_CONVERSATIONS,
      KeyConditionExpression: 'userId = :uid',
      FilterExpression: 'recordType = :type',
      ExpressionAttributeValues: { ':uid': userId, ':type': 'report' },
    })
  );

  const items = result.Items || [];

  const reports = await Promise.all(
    items.map(async (item) => {
      const downloadUrl = await getSignedUrl(
        s3Client,
        new GetObjectCommand({ Bucket: process.env.REPORTS_BUCKET, Key: item.s3Key }),
        { expiresIn: 3600 }
      );
      return {
        reportId: item.recordId.replace('report#', ''),
        date: item.reportDate,
        summary: item.content,
        fromDate: item.fromDate || null,
        toDate: item.toDate || null,
        symptomCount: item.symptomCount || 0,
        downloadUrl,
      };
    })
  );

  return response(200, reports);
}

exports.handler = async (event) => {
  if (configError) {
    console.error(configError);
    return response(500, { message: 'Service configuration error. Please contact support.' });
  }

  const method = event.httpMethod;
  const path = event.path;
  const userId = event.requestContext?.authorizer?.claims?.sub;

  try {
    if (method === 'POST' && path === '/reports/generate') {
      return await handleGenerateReport(userId, event.body);
    }
    if (method === 'GET' && path === '/reports') {
      return await handleGetReports(userId);
    }
    return response(404, { message: 'Route not found.' });
  } catch (err) {
    console.error('Unhandled error:', err);
    return response(500, { message: 'Something went wrong. Please try again shortly.' });
  }
};
